/// <reference types="@codetrix-studio/capacitor-google-auth" />
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig & {
  android: {
    allowMixedContent: boolean;
    adjustResize: boolean;
  };
} = {
  // Reverse-DNS identifier used by Android and the Play Store.
  appId: 'com.nritaxai.app', // Reverse-domain notation guarantees a globally unique package id required by Android and the Play Store.
  // Human-readable app name shown on the device.
  appName: 'Nritaxai',
  // Folder generated by `vite build` that Capacitor copies into the native app.
  webDir: 'dist',
  android: {
    allowMixedContent: true, // Keep Android WebView permissive enough for mixed-content edge cases inside embedded auth/payment flows.
    adjustResize: true, // Request viewport resize behavior so the chat composer stays visible above the Android keyboard.
  },
  // Keep the default production config free of any live-reload dev server URL.
  server: {
    // Allow emulator builds to talk to a local HTTP API such as 10.0.2.2:5000.
    cleartext: true,
    // Force HTTPS for externally hosted content when navigation is allowed.
    androidScheme: 'https',
    iosScheme: 'https',
    // Domains the WebView is allowed to navigate to during auth and payments.
    allowNavigation: [
      'nritax.ai',
      '*.nritax.ai',
      'appleid.apple.com',
      'appleid.cdn-apple.com',
      'checkout.razorpay.com',
      'accounts.google.com',
      '10.0.2.2',
    ],
  },
  plugins: {
    GoogleAuth: {
      scopes: ['profile', 'email'], // Request the basic Google profile scopes required for sign-in.
      serverClientId: '307987125319-8ioooqfm0iel5c0d4smmg1l204p7dtjm.apps.googleusercontent.com', // Use the Web OAuth client ID for the backend auth code exchange expected by the Android plugin.
      clientId: '307987125319-8ioooqfm0iel5c0d4smmg1l204p7dtjm.apps.googleusercontent.com', // Use the same Web OAuth client ID as the plugin's primary Google sign-in identifier.
      forceCodeForRefreshToken: true, // Force Google to return a server auth code that can be exchanged for refresh-capable tokens.
      androidClientId: '307987125319-8ioooqfm0iel5c0d4smmg1l204p7dtjm.apps.googleusercontent.com', // Keep Android aligned with the same Web OAuth client ID to avoid DEVELOPER_ERROR mismatches.
    },
    SplashScreen: {
      // Show the native splash while the web bundle is loading.
      launchShowDuration: 2000,
      // Auto-hide once the app is ready unless you choose to control it manually.
      launchAutoHide: true,
      // Match the app brand background behind the splash asset.
      backgroundColor: '#ffffff',
      // Use a centered asset without full-screen scaling.
      androidSplashResourceName: 'splash',
      // Keep the full NRITAX logo visible on Android splash screens without cropping the .AI wordmark.
      androidScaleType: 'FIT_CENTER',
      // Keep the splash behind the status bar for a clean launch.
      showSpinner: false,
    },
  },
};

export default config;
