/// <reference types="@codetrix-studio/capacitor-google-auth" />
import type { CapacitorConfig } from '@capacitor/cli';

const GOOGLE_WEB_CLIENT_ID = "307987125319-k7ifrilh3a9f2bb24p263hsj7k6j1fjq.apps.googleusercontent.com";

const config: CapacitorConfig = {
  // Reverse-DNS identifier used by Android and the Play Store.
  appId: 'com.nritaxai.app', // Reverse-domain notation guarantees a globally unique package id required by Android and the Play Store.
  // Human-readable app name shown on the device.
  appName: 'Nritaxai',
  // Folder generated by `vite build` that Capacitor copies into the native app.
  webDir: 'dist',
  // Keep the default production config free of any live-reload dev server URL.
  server: {
    // Allow emulator builds to talk to a local HTTP API such as 10.0.2.2:5000.
    cleartext: true,
    // Force HTTPS for externally hosted content when navigation is allowed.
    androidScheme: 'https',
    iosScheme: 'https',
    // Domains the WebView is allowed to navigate to during auth and payments.
    allowNavigation: [
      'nritax.ai',
      '*.nritax.ai',
      'appleid.apple.com',
      'appleid.cdn-apple.com',
      'checkout.razorpay.com',
      'accounts.google.com',
      '10.0.2.2',
    ],
  },
  plugins: {
    GoogleAuth: {
      clientId: GOOGLE_WEB_CLIENT_ID,
      scopes: ["profile", "email"],
      serverClientId: GOOGLE_WEB_CLIENT_ID,
      forceCodeForRefreshToken: false,
    },
    SplashScreen: {
      // Show the native splash while the web bundle is loading.
      launchShowDuration: 2000,
      // Auto-hide once the app is ready unless you choose to control it manually.
      launchAutoHide: true,
      // Match the app brand background behind the splash asset.
      backgroundColor: '#ffffff',
      // Use a centered asset without full-screen scaling.
      androidSplashResourceName: 'splash',
      // Prevent stretching on devices with different aspect ratios.
      androidScaleType: 'CENTER_CROP',
      // Keep the splash behind the status bar for a clean launch.
      showSpinner: false,
    },
  },
};

export default config;
