import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  // Reverse-DNS identifier used by Android and the Play Store.
  appId: 'com.nritaxai.app', // Reverse-domain notation guarantees a globally unique package id required by Android and the Play Store.
  // Human-readable app name shown on the device.
  appName: 'Nritaxai',
  // Folder generated by `vite build` that Capacitor copies into the native app.
  webDir: 'dist',
  server: {
    // Replace this with your machine-reachable dev server URL for live reload.
    url: 'http://YOUR_LOCAL_IP_OR_HOST:5173',
    // Allow Android to connect to a non-HTTPS local development server.
    cleartext: true,
    // Use HTTP while connecting to a local development server.
    androidScheme: 'http',
    iosScheme: 'http',
    // Domains the WebView is allowed to navigate to during auth and payments.
    allowNavigation: [
      'nritax.ai',
      '*.nritax.ai',
      'appleid.apple.com',
      'appleid.cdn-apple.com',
      'checkout.razorpay.com',
      'accounts.google.com',
      'YOUR_LOCAL_IP_OR_HOST',
    ],
  },
  plugins: {
    GoogleAuth: {
      scopes: ['profile', 'email'], // Request the basic Google profile scopes required for sign-in.
      serverClientId: '307987125319-k7ifrilh3a9f2bb24p263hsj7k6j1fjq.apps.googleusercontent.com', // Use the confirmed Web Client ID because Android returns a server auth code that must be exchanged against the web OAuth client.
      clientId: '307987125319-k7ifrilh3a9f2bb24p263hsj7k6j1fjq.apps.googleusercontent.com', // Use the same Web Client ID here so the plugin stays aligned with the backend token exchange flow instead of an Android-only OAuth client.
      androidClientId: '307987125319-k7ifrilh3a9f2bb24p263hsj7k6j1fjq.apps.googleusercontent.com', // Keep Android pointed at the same Web Client ID so native sign-in and backend verification use one consistent OAuth audience.
      forceCodeForRefreshToken: true, // Force Google to return a server auth code that can be exchanged for refresh-capable tokens.
    },
    SplashScreen: {
      // Show the native splash while the web bundle is loading.
      launchShowDuration: 2000,
      // Auto-hide once the app is ready unless you choose to control it manually.
      launchAutoHide: true,
      // Match the app brand background behind the splash asset.
      backgroundColor: '#ffffff',
      // Use a centered asset without full-screen scaling.
      androidSplashResourceName: 'splash',
      // Prevent stretching on devices with different aspect ratios.
      androidScaleType: 'CENTER_CROP',
      // Keep launch visuals clean by hiding the spinner.
      showSpinner: false,
    },
  },
};

export default config;
