namespace: nritax-production

resources:
  - ../../base

patches:
  - target:
      kind: Rollout
      name: nritax-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_REGION
          value: us-central1
  - target:
      kind: Deployment
      name: nritax-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_REGION
          value: us-central1
  - target:
      kind: Deployment
      name: nritax-worker-priority
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_REGION
          value: us-central1
  - target:
      kind: Deployment
      name: nritax-worker-batch
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_REGION
          value: us-central1
  - target:
      kind: Deployment
      name: nritax-worker-ai
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_REGION
          value: us-central1
  - target:
      kind: Deployment
      name: nritax-gpu-worker
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_REGION
          value: us-central1
