const freezeCountryRule = (rule) => Object.freeze({ ...rule, supportedPlans: Object.freeze([...(rule.supportedPlans || [])]) });

export const DEFAULT_COUNTRY_CODE = "IN";

export const COUNTRY_RULES = Object.freeze({
  IN: freezeCountryRule({
    code: "IN",
    name: "India",
    currency: "INR",
    pricingRegion: "domestic_india",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "resident_india",
    aiComplianceMode: "india_resident",
    supportedDisplayCurrencies: ["INR"],
  }),
  US: freezeCountryRule({
    code: "US",
    name: "United States",
    currency: "USD",
    pricingRegion: "international_us",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_us",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["USD", "INR"],
  }),
  GB: freezeCountryRule({
    code: "GB",
    name: "United Kingdom",
    currency: "GBP",
    pricingRegion: "international_uk",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_uk",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["GBP", "INR"],
  }),
  AE: freezeCountryRule({
    code: "AE",
    name: "United Arab Emirates",
    currency: "AED",
    pricingRegion: "gcc",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_gcc",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["AED", "INR"],
  }),
  SG: freezeCountryRule({
    code: "SG",
    name: "Singapore",
    currency: "SGD",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_singapore",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["SGD", "INR"],
  }),
  CA: freezeCountryRule({
    code: "CA",
    name: "Canada",
    currency: "CAD",
    pricingRegion: "north_america",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_canada",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["CAD", "INR"],
  }),
  AU: freezeCountryRule({
    code: "AU",
    name: "Australia",
    currency: "AUD",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_australia",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["AUD", "INR"],
  }),
  BH: freezeCountryRule({
    code: "BH",
    name: "Bahrain",
    currency: "BHD",
    pricingRegion: "gcc",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_gcc",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["BHD", "INR"],
  }),
  CH: freezeCountryRule({
    code: "CH",
    name: "Switzerland",
    currency: "CHF",
    pricingRegion: "europe",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_europe",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["CHF", "INR"],
  }),
  DE: freezeCountryRule({
    code: "DE",
    name: "Germany",
    currency: "EUR",
    pricingRegion: "europe",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_europe",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["EUR", "INR"],
  }),
  FR: freezeCountryRule({
    code: "FR",
    name: "France",
    currency: "EUR",
    pricingRegion: "europe",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_europe",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["EUR", "INR"],
  }),
  HK: freezeCountryRule({
    code: "HK",
    name: "Hong Kong",
    currency: "HKD",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_apac",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["HKD", "INR"],
  }),
  ID: freezeCountryRule({
    code: "ID",
    name: "Indonesia",
    currency: "IDR",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_apac",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["IDR", "INR"],
  }),
  IE: freezeCountryRule({
    code: "IE",
    name: "Ireland",
    currency: "EUR",
    pricingRegion: "europe",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_europe",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["EUR", "INR"],
  }),
  JP: freezeCountryRule({
    code: "JP",
    name: "Japan",
    currency: "JPY",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_apac",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["JPY", "INR"],
  }),
  KW: freezeCountryRule({
    code: "KW",
    name: "Kuwait",
    currency: "KWD",
    pricingRegion: "gcc",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_gcc",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["KWD", "INR"],
  }),
  MY: freezeCountryRule({
    code: "MY",
    name: "Malaysia",
    currency: "MYR",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_apac",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["MYR", "INR"],
  }),
  NL: freezeCountryRule({
    code: "NL",
    name: "Netherlands",
    currency: "EUR",
    pricingRegion: "europe",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_europe",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["EUR", "INR"],
  }),
  NZ: freezeCountryRule({
    code: "NZ",
    name: "New Zealand",
    currency: "NZD",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_apac",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["NZD", "INR"],
  }),
  OM: freezeCountryRule({
    code: "OM",
    name: "Oman",
    currency: "OMR",
    pricingRegion: "gcc",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_gcc",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["OMR", "INR"],
  }),
  QA: freezeCountryRule({
    code: "QA",
    name: "Qatar",
    currency: "QAR",
    pricingRegion: "gcc",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_gcc",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["QAR", "INR"],
  }),
  SA: freezeCountryRule({
    code: "SA",
    name: "Saudi Arabia",
    currency: "SAR",
    pricingRegion: "gcc",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_gcc",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["SAR", "INR"],
  }),
  SE: freezeCountryRule({
    code: "SE",
    name: "Sweden",
    currency: "SEK",
    pricingRegion: "europe",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_europe",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["SEK", "INR"],
  }),
  TH: freezeCountryRule({
    code: "TH",
    name: "Thailand",
    currency: "THB",
    pricingRegion: "apac",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_apac",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["THB", "INR"],
  }),
  ZA: freezeCountryRule({
    code: "ZA",
    name: "South Africa",
    currency: "ZAR",
    pricingRegion: "africa",
    supportedPlans: ["starter", "professional", "enterprise"],
    taxWorkflow: "nri_africa",
    aiComplianceMode: "nri_cross_border",
    supportedDisplayCurrencies: ["ZAR", "INR"],
  }),
});

export const COUNTRY_NAME_TO_CODE = Object.freeze(
  Object.values(COUNTRY_RULES).reduce((acc, rule) => {
    acc[rule.name.toLowerCase()] = rule.code;
    return acc;
  }, {})
);

export const CHECKOUT_DISPLAY_CURRENCY_MATRIX = Object.freeze(
  Object.values(COUNTRY_RULES).reduce((acc, rule) => {
    acc[rule.code] = [...rule.supportedDisplayCurrencies];
    return acc;
  }, {})
);
