import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image
} from "@react-pdf/renderer";

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.6,
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottom: "1 solid #E5E7EB",
    paddingBottom: 10,
  },

  logo: {
    width: 120,
  },

  titleSection: {
    marginBottom: 20,
  },

  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
  },

  subtitle: {
    fontSize: 12,
    color: "#6B7280",
  },

  table: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },

  tableRow: {
    flexDirection: "row",
  },

  tableHeader: {
    backgroundColor: "#F3F4F6",
    fontWeight: "bold",
  },

  tableCell: {
    flex: 1,
    padding: 8,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#E5E7EB",
  },

  disclaimerSection: {
    marginTop: 30,
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: "#E5E7EB",
  },

  disclaimerTitle: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 6,
  },

  disclaimerText: {
    fontSize: 9,
    color: "#6B7280",
  }
});

interface Props {
  userName: string;
  reportData: Array<{ label: string; value: string }>;
}

export const TaxReportPDF = ({ userName, reportData }: Props) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* HEADER */}
      <View style={styles.header}>
        <Image
          style={styles.logo}
          src="/logo.png"  // Replace with hosted URL if needed
        />
        <Text>NRITAX AI Report</Text>
      </View>

      {/* TITLE SECTION */}
      <View style={styles.titleSection}>
        <Text style={styles.title}>Tax Advisory Summary</Text>
        <Text style={styles.subtitle}>
          Generated for: {userName}
        </Text>
        <Text style={styles.subtitle}>
          Date: {new Date().toLocaleDateString()}
        </Text>
      </View>

      {/* TABLE */}
      <View style={styles.table}>
        {/* Header Row */}
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={styles.tableCell}>Description</Text>
          <Text style={styles.tableCell}>Details</Text>
        </View>

        {/* Dynamic Rows */}
        {reportData.map((item, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.tableCell}>{item.label}</Text>
            <Text style={styles.tableCell}>{item.value}</Text>
          </View>
        ))}
      </View>

      {/* DISCLAIMER */}
      <View style={styles.disclaimerSection}>
        <Text style={styles.disclaimerTitle}>
          Disclaimer
        </Text>
        <Text style={styles.disclaimerText}>
          This report is generated by NRITAX AI for informational purposes only.
          It does not constitute professional tax advice. Users should consult
          a licensed tax professional before making financial decisions.
          NRITAX AI does not assume liability for decisions made based on this report.
        </Text>
      </View>

    </Page>
  </Document>
);
