namespace: nritax-production

resources:
  - api-rollout.yaml
  - api-services.yaml
  - worker-deployment.yaml
  - gpu-worker-deployment.yaml
  - worker-service.yaml
  - api-hpa.yaml
  - worker-hpa.yaml
  - pdb.yaml
