import React from "react";
import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const h = React.createElement;

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.6,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottom: "1 solid #E2E8F0",
    paddingBottom: 10,
  },
  brand: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2563EB",
  },
  titleSection: {
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12,
    color: "#0F172A",
  },
  table: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  tableRow: {
    flexDirection: "row",
  },
  tableHeader: {
    backgroundColor: "#F7FAFC",
    fontWeight: "bold",
  },
  tableCell: {
    flex: 1,
    padding: 8,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#E2E8F0",
  },
  disclaimerSection: {
    marginTop: 30,
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: "#E2E8F0",
  },
  disclaimerTitle: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 6,
  },
  disclaimerText: {
    fontSize: 9,
    color: "#0F172A",
  },
});

const buildRows = (reportData) =>
  reportData.map((item, index) =>
    h(
      View,
      { key: `${item.label}-${index}`, style: styles.tableRow },
      h(Text, { style: styles.tableCell }, item.label),
      h(Text, { style: styles.tableCell }, item.value)
    )
  );

export function TaxReportPDF({ userName, reportData }) {
  return h(
    Document,
    null,
    h(
      Page,
      { size: "A4", style: styles.page },
      h(
        View,
        { style: styles.header },
        h(Text, { style: styles.brand }, "NRITAX AI"),
        h(Text, null, "NRITAX AI Report")
      ),
      h(
        View,
        { style: styles.titleSection },
        h(Text, { style: styles.title }, "Tax Advisory Summary"),
        h(Text, { style: styles.subtitle }, `Generated for: ${userName}`),
        h(Text, { style: styles.subtitle }, `Date: ${new Date().toLocaleDateString()}`)
      ),
      h(
        View,
        { style: styles.table },
        h(
          View,
          { style: [styles.tableRow, styles.tableHeader] },
          h(Text, { style: styles.tableCell }, "Description"),
          h(Text, { style: styles.tableCell }, "Details")
        ),
        ...buildRows(reportData)
      ),
      h(
        View,
        { style: styles.disclaimerSection },
        h(Text, { style: styles.disclaimerTitle }, "Disclaimer"),
        h(
          Text,
          { style: styles.disclaimerText },
          "This report is generated by NRITAX AI for informational purposes only. It does not constitute professional tax advice. Users should consult a licensed tax professional before making financial decisions. NRITAX AI does not assume liability for decisions made based on this report."
        )
      )
    )
  );
}
