import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

type PrimitiveValue = string | number | boolean | null | undefined;

type ReportField = {
  label: string;
  value: PrimitiveValue;
};

type ReportSectionInput = ReportField[] | Record<string, PrimitiveValue> | null | undefined;

type TaxReportInput =
  | ReportField[]
  | {
      userName?: string;
      fileName?: string;
      taxpayerInfo?: ReportSectionInput;
      incomeSummary?: ReportSectionInput;
      deductions?: ReportSectionInput;
      taxCalculation?: ReportSectionInput;
      disclaimer?: string | string[];
      reportData?: ReportField[];
    };

type NormalizedSection = {
  title: string;
  rows: Array<[string, string]>;
};

const DEFAULT_DISCLAIMER =
  "This report is generated by NRITAX AI for informational purposes only. It does not constitute professional tax advice. Users should consult a licensed tax professional before making financial decisions. NRITAX AI does not assume liability for decisions made based on this report.";

const formatValue = (value: PrimitiveValue) => {
  if (value === null || value === undefined || value === "") {
    return "Not provided";
  }

  return String(value);
};

const toRows = (section: ReportSectionInput): Array<[string, string]> => {
  if (!section) {
    return [];
  }

  if (Array.isArray(section)) {
    return section
      .filter((item) => item?.label)
      .map((item) => [item.label, formatValue(item.value)]);
  }

  return Object.entries(section).map(([label, value]) => [label, formatValue(value)]);
};

const classifyFallbackSection = (label: string) => {
  const normalized = label.toLowerCase();

  if (/(name|pan|tan|resident|residency|country|citizenship|assessment|filing|language|taxpayer)/.test(normalized)) {
    return "taxpayerInfo";
  }

  if (/(deduction|80c|80d|exemption|hra|relief|rebate)/.test(normalized)) {
    return "deductions";
  }

  if (/(tax|cess|surcharge|tds|refund|payable|liability)/.test(normalized)) {
    return "taxCalculation";
  }

  return "incomeSummary";
};

const normalizeReport = (reportData: TaxReportInput) => {
  const sections: Record<"taxpayerInfo" | "incomeSummary" | "deductions" | "taxCalculation", Array<[string, string]>> = {
    taxpayerInfo: [],
    incomeSummary: [],
    deductions: [],
    taxCalculation: [],
  };

  let fileName = "nritax-report.pdf";
  let userName = "";
  let disclaimerLines: string[] = [DEFAULT_DISCLAIMER];

  if (Array.isArray(reportData)) {
    for (const field of reportData) {
      if (!field?.label) continue;
      sections[classifyFallbackSection(field.label)].push([field.label, formatValue(field.value)]);
    }
  } else if (reportData && typeof reportData === "object") {
    userName = formatValue(reportData.userName).replace(/^Not provided$/, "");
    if (reportData.fileName?.trim()) {
      fileName = reportData.fileName.trim();
    }

    if (reportData.disclaimer) {
      disclaimerLines = Array.isArray(reportData.disclaimer) ? reportData.disclaimer : [reportData.disclaimer];
    }

    sections.taxpayerInfo.push(...toRows(reportData.taxpayerInfo));
    sections.incomeSummary.push(...toRows(reportData.incomeSummary));
    sections.deductions.push(...toRows(reportData.deductions));
    sections.taxCalculation.push(...toRows(reportData.taxCalculation));

    for (const field of reportData.reportData || []) {
      if (!field?.label) continue;
      sections[classifyFallbackSection(field.label)].push([field.label, formatValue(field.value)]);
    }
  }

  if (userName && !sections.taxpayerInfo.some(([label]) => label.toLowerCase() === "name")) {
    sections.taxpayerInfo.unshift(["Name", userName]);
  }

  const orderedSections: NormalizedSection[] = [
    { title: "Taxpayer Information", rows: sections.taxpayerInfo },
    { title: "Income Summary", rows: sections.incomeSummary },
    { title: "Deductions", rows: sections.deductions },
    { title: "Tax Calculation", rows: sections.taxCalculation },
  ];

  return {
    fileName,
    userName,
    disclaimerLines,
    sections: orderedSections,
  };
};

const buildSafeFileName = (fileName: string, userName: string) => {
  const baseName = fileName.trim() || (userName ? `${userName}-tax-report.pdf` : "nritax-report.pdf");
  return baseName.replace(/[<>:"/\\|?*\u0000-\u001F]+/g, "-");
};

export function generateTaxReportPDF(reportData: TaxReportInput) {
  const { fileName, userName, disclaimerLines, sections } = normalizeReport(reportData);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageMargin = 40;
  const contentWidth = pageWidth - pageMargin * 2;
  const generatedOn = new Date().toLocaleDateString();

  // Set the brand color before drawing the report header.
  doc.setTextColor(37, 99, 235);
  // Draw the NRITAX brand at the top of the first page.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("NRITAX AI", pageMargin, 48);

  // Draw the report label aligned to the right side of the header row.
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.text("NRITAX AI Report", pageWidth - pageMargin, 48, { align: "right" });

  // Draw a divider line below the header to separate branding from content.
  doc.setDrawColor(226, 232, 240);
  doc.line(pageMargin, 62, pageWidth - pageMargin, 62);

  // Draw the main title that introduces the report body.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Tax Advisory Summary", pageMargin, 92);

  // Draw the generated-for label using dynamic user data from the report payload.
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Generated for: ${userName || "Taxpayer"}`, pageMargin, 112);

  // Draw the generation date so the downloaded report shows when it was created.
  doc.text(`Date: ${generatedOn}`, pageMargin, 128);

  let currentY = 152;

  for (const section of sections) {
    const rows = section.rows.length ? section.rows : [["Status", "No details available"]];

    // Draw the section heading before the table for that part of the report.
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(section.title, pageMargin, currentY);

    autoTable(doc, {
      startY: currentY + 8,
      margin: { left: pageMargin, right: pageMargin },
      head: [["Description", "Details"]],
      body: rows,
      theme: "grid",
      styles: {
        font: "helvetica",
        fontSize: 10,
        cellPadding: 8,
        lineColor: [226, 232, 240],
        lineWidth: 1,
        textColor: [15, 23, 42],
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: [247, 250, 252],
        textColor: [15, 23, 42],
        fontStyle: "bold",
      },
      columnStyles: {
        0: { cellWidth: 170, fontStyle: "bold" },
        1: { cellWidth: contentWidth - 170 },
      },
      didDrawPage: (data) => {
        // Re-draw the page number in the footer whenever autoTable adds a new page.
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(100, 116, 139);
        doc.text(`Page ${data.pageNumber}`, pageWidth - pageMargin, pageHeight - 18, { align: "right" });
      },
    });

    currentY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY
      ? ((doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY as number) + 24
      : currentY + 40;
  }

  if (currentY > pageHeight - 110) {
    // Add a new page when there is not enough room left for the disclaimer block.
    doc.addPage();
    currentY = pageMargin + 10;
  }

  // Draw a divider above the disclaimer section at the end of the report.
  doc.setDrawColor(226, 232, 240);
  doc.line(pageMargin, currentY, pageWidth - pageMargin, currentY);

  // Draw the disclaimer heading so readers can quickly identify the final legal note.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Disclaimer", pageMargin, currentY + 20);

  // Wrap the disclaimer text to the printable width before writing it to the page.
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const disclaimerText = disclaimerLines.filter(Boolean).join("\n\n");
  const wrappedDisclaimer = doc.splitTextToSize(disclaimerText, contentWidth);
  // Render the wrapped disclaimer lines as multi-line text in the footer section.
  doc.text(wrappedDisclaimer, pageMargin, currentY + 38);

  // Trigger the browser download for the finished PDF file.
  doc.save(buildSafeFileName(fileName, userName));
}
