import { CONTACT_WHATSAPP } from "../../config/appConfig";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";

const sections = [
  {
    title: "1. No Professional Advice",
    points: [
      "The content generated by our AI chatbot and available on this website does not constitute legal, tax, or financial advice.",
      "Users are advised to consult a qualified Chartered Accountant, CPA, or tax professional before making any financial or tax-related decisions.",
    ],
  },
  {
    title: "2. Accuracy of Information",
    points: [
      "While we strive to provide accurate and up-to-date information, tax laws and regulations are subject to change.",
      "We do not guarantee the completeness, accuracy, or reliability of any information.",
    ],
  },
  {
    title: "3. AI-Generated Responses",
    points: [
      "Our platform uses artificial intelligence to generate responses.",
      "Outputs may sometimes be incomplete, outdated, or incorrect.",
      "Users should verify information independently before relying on it.",
    ],
  },
  {
    title: "4. Limitation of Liability",
    points: [
      "Nritax.ai shall not be held liable for any losses, damages, or liabilities arising from the use of our platform.",
      "Nritax.ai shall not be held liable for decisions made based on AI-generated or website content.",
    ],
  },
  {
    title: "5. Third-Party Services",
    points: [
      "Our website may include links or integrations with third-party services.",
      "We are not responsible for their content, policies, or practices.",
      "Use of third-party services is at your own risk.",
    ],
  },
  {
    title: "6. User Responsibility",
    points: [
      "By using this platform, you agree that you are responsible for the accuracy of the information you provide.",
      "By using this platform, you agree that you will use the platform only for lawful purposes.",
    ],
  },
  {
    title: "7. No Guarantees",
    points: [
      "We do not guarantee specific tax outcomes.",
      "We do not guarantee refunds, savings, or financial results.",
      "We do not guarantee continuous or error-free service availability.",
    ],
  },
  {
    title: "8. Changes to Disclaimer",
    points: [
      "We reserve the right to update or modify this Disclaimer at any time. Updates will be reflected on this page.",
    ],
  },
  {
    title: "9. Contact Us",
    points: [
      "If you have any questions regarding this Disclaimer, please contact support@nritax.ai.",
      `Contact Number: ${CONTACT_WHATSAPP}`,
    ],
  },
] as const;

export function Disclaimer() {
  return (
    <main className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <Card className="rounded-2xl border-[#E2E8F0] bg-[#F7FAFC]">
        <CardHeader className="space-y-3">
          <CardTitle className="text-3xl text-[#0F172A] sm:text-4xl">Disclaimer</CardTitle>
          <CardDescription className="text-base text-[#0F172A]">Last Updated: March 17, 2026</CardDescription>
          <p className="text-sm text-[#0F172A]">
            The information provided on Nritax.ai is for general informational purposes only. By using our platform,
            you acknowledge and agree to the terms outlined in this disclaimer.
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          {sections.map((section) => (
            <section key={section.title} className="rounded-xl border border-[#E2E8F0] bg-white p-4">
              <h2 className="text-lg font-semibold text-[#0F172A]">{section.title}</h2>
              <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-[#0F172A]">
                {section.points.map((point) => (
                  <li key={point}>{point}</li>
                ))}
              </ul>
            </section>
          ))}
        </CardContent>
      </Card>
    </main>
  );
}
